package me.newsong.domain.entity;

import me.newsong.enums.DeptStatus;

import java.io.Serializable;
import java.util.List;

public class DepartmentDO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_name
     *
     * @mbggenerated
     */
    private String deptName;


    private List<EmployeeDO> emps;


    private DeptStatus deptStatus;

    public DepartmentDO(Integer id, String deptName, DeptStatus deptStatus) {
        this.id = id;
        this.deptName = deptName;
        this.deptStatus = deptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated
     */
    public DepartmentDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.id
     *
     * @return the value of dept.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.id
     *
     * @param id the value for dept.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_name
     *
     * @return the value of dept.dept_name
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_name
     *
     * @param deptName the value for dept.dept_name
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    public List<EmployeeDO> getEmps() {
        return emps;
    }

    public void setEmps(List<EmployeeDO> emps) {
        this.emps = emps;
    }

    public DeptStatus getDeptStatus() {
        return deptStatus;
    }

    public void setDeptStatus(DeptStatus deptStatus) {
        this.deptStatus = deptStatus;
    }

    @Override
    public String toString() {
        return "DepartmentDO{" +
                "id=" + id +
                ", deptName='" + deptName + '\'' +
                ", emps=" + emps +
                ", status=" + deptStatus +
                '}';
    }
}