package me.newsong.dao;

import me.newsong.domain.common.PageBean;
import me.newsong.domain.entity.EmployeeDO;

import java.util.List;

public interface EmployeeDOMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int insert(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int insertSelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    EmployeeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmployeeDO record);
    List<EmployeeDO> findAllEmployees();
    
    List<EmployeeDO> findEmployeesByPage(PageBean<EmployeeDO> page);
    int getCount();
}