package me.newsong.dao;

import com.github.pagehelper.Page;
import me.newsong.domain.entity.EmployeeDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmployeeDOMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int insert(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int insertSelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    EmployeeDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmployeeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmployeeDO record);
    Page<EmployeeDO> findAllEmployees(@Param("pageNum") int pageNum, @Param("pageSize") int pageSize);
    int getCount();
    EmployeeDO findCascadeById(Integer id);
    List<EmployeeDO> findByDept(Integer id);
    EmployeeDO findDiscriminatorById(Integer id);
}